Documentation:
  Enabled: false
LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
