name             'atomic'
maintainer       'Chef Partner Engineering'
maintainer_email 'partnereng@chef.io'
license          'Apache 2.0'
description      'Provides resources for bootstrapping Atomic Masters and Minions'
long_description 'Provides resources for bootstrapping Atomic Masters and Minions'
version          '0.1.0'
